name             'redmine'
maintainer       'ClouDesire'
maintainer_email 'dev@cloudesire.com'
license          'All rights reserved'
description      'Installs/Configures Redmine with unicorn'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'apt'
depends          'database'
depends          'mysql'
depends          'application'
